### ISSUE TITLE
[Question] 为什么消息中的数字采用二位数字对齐

### ISSUE THREAD

**Issue by SherkeyXD** [theTeamFuture/nonebot-plugin-lynchpined#1]
https://github.com/theTeamFuture/nonebot-plugin-lynchpined/blob/ee6de52e36f13535aef9f005b04eae4a053f5d18/nonebot_plugin_lynchpined/__init__.py#L51

对于个位数不美观（尤其是被框起来的部分）
```
Lynchpin: 4%
Pattern Matched:
 0 [ 4] 12 15 24 33 34 35 35
```

**Comment by 050644zf** [comment]
我觉得对齐好看点，如果有需要可以自行修改
